### ISSUE TITLE
[Bug] Doesn't render.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [VishwaGauravIn/visit-count-pro#12]
As https://github.com/VishwaGauravIn/visit-count-pro/issues/11#issue-2322043405 explains, if I don't replace `/>` with `>`, it is invisible. However, when I delete that, as https://github.com/RokeJulianLockhart/rokejulianlockhart/blob/fbfc267ebb9920a6237b87f810f13a3658e3ba76/readMe.md?plain=1#L86:~:text=%3Ctd%3E%20%3Ca%20href=%22https://visitcount.itsvg.in%22%3E%20%3Cimg%20src=%22https://visitcount.itsvg.in/api?id=RokeJulianLockhart%26label=Profile%2520Views%26color=12%26icon=0%26pretty=false%22%3E

<blockQuote>

```HTML
<table><tr>
	<th> Summary </th>
	<td> <img src="https://github-readme-stats.vercel.app/api?username=rokejulianlockhart&theme=transparent&hide_border=true&include_all_commits=true&count_private=true"> </td>
</tr><tr>
	<th> Languages </th>
	<td> <img src="https://github-readme-stats.vercel.app/api/top-langs/?username=RokeJulianLockhart&theme=transparent&hide_border=true&include_all_commits=false&count_private=false&layout=compact"> </td>
</tr><tr>
	<th> Trophies </th>
	<td> <img src="https://github-profile-trophy.vercel.app/?username=RokeJulianLockhart&theme=default&no-frame=false&no-bg=false&margin-w=4"> </td>
</tr><tr>
	<th> Visitation </th>
	<td> <a href="https://visitcount.itsvg.in"> <img src="https://visitcount.itsvg.in/api?id=RokeJulianLockhart&label=Profile%20Views&color=12&icon=0&pretty=false"> </a>
</td>
</tr></table>
```

</blockQuote>

demonstrates, it merely displays a broken image icon from the browser.

**Comment by VishwaGauravIn** [comment]
Today's limit for the database is reached, it will start working fine from tomorrow.
