### ISSUE TITLE
Cant center

### ISSUE THREAD

**Issue by v6r** [VishwaGauravIn/visit-count-pro#4]
```
<p align="center">
    <img src="https://visitcount.itsvg.in/api?id=v6r&label=Profile%20Views&color=12&icon=2&pretty=true" alt="Profile Views">
</p>
```
should center it in the readme but it only pushes it a bit. If you marker it his pops up. So its centered.
![image](https://user-images.githubusercontent.com/83277314/173206627-cef1f143-5ce5-4512-858b-49bd7292fdd5.png)
![image](https://user-images.githubusercontent.com/83277314/173206628-79deaf14-563b-4ff2-bedc-b871e92af62b.png)

**Comment by VishwaGauravIn** [comment]
Sorry @v6r for the late response, Issue has been fixed. Thanks for your valuable feedback.
