### ISSUE TITLE
Internal Server Error: Link is not working

### ISSUE THREAD

**Issue by N-dcool** [VishwaGauravIn/visit-count-pro#6]
<img width="933" alt="Screenshot 2023-03-03 at 4 37 41 PM" src="https://user-images.githubusercontent.com/107427909/222705302-70d6aa84-26b2-443f-b1d8-24ca6a4de2bb.png">
few days before I notice my visit count is not visible in my Readme profile, so I visited my visit count link it was showing 

 ```INTERNAL SERVER ERROR```
 my visit counter link: https://visitcount.itsvg.in/api?id=Nareshchoudhary02&icon=0&color=0

**Comment by VishwaGauravIn** [comment]
Status: Fixed
Issue: Netlify Emulator Restart

**Comment by N-dcool** [comment]
same issue again :(

**Comment by N-dcool** [comment]
@VishwaGauravIn

**Comment by VishwaGauravIn** [comment]
> same issue again :(

Issue has been fixed, it was due to server shift. It hopefully won't happen again. Thanks for informing me.

**Comment by san-veer** [comment]
@VishwaGauravIn same issue still is happening again
